name:                normalizer
version:             0.1.0.0
github:              "justus-wendroth/normalizer"
license:             BSD3
author:              "Justus Wendroth"
maintainer:          "justus.wendroth@outlook.de"
copyright:           "2021 Justus Wendroth"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/normalizer#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  normalizer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - normalizer

tests:
  normalizer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - normalizer
